#############################################################################
# Generated by PAGE version 8.0
#  in conjunction with Tcl version 8.6
#  Feb 06, 2024 10:20:54 PM CET  platform: Windows NT
set vTcl(timestamp) ""
if {![info exists vTcl(borrow)]} {
    ::vTcl::MessageBox -title Error -message  "You must open project files from within PAGE."
    exit}


set vTcl(actual_gui_font_dft_desc)  TkDefaultFont
set vTcl(actual_gui_font_dft_name)  TkDefaultFont
set vTcl(actual_gui_font_text_desc)  TkTextFont
set vTcl(actual_gui_font_text_name)  TkTextFont
set vTcl(actual_gui_font_fixed_desc)  TkFixedFont
set vTcl(actual_gui_font_fixed_name)  TkFixedFont
set vTcl(actual_gui_font_menu_desc)  TkMenuFont
set vTcl(actual_gui_font_menu_name)  TkMenuFont
set vTcl(actual_gui_font_tooltip_desc)  TkDefaultFont
set vTcl(actual_gui_font_tooltip_name)  TkDefaultFont
set vTcl(actual_gui_font_treeview_desc)  TkDefaultFont
set vTcl(actual_gui_font_treeview_name)  TkDefaultFont
########################################### 
set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) gray40
set vTcl(analog_color_p) #c3c3c3
set vTcl(analog_color_m) beige
set vTcl(tabfg1) black
set vTcl(tabfg2) white
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(actual_gui_menu_active_fg)  #000000
########################################### 
set vTcl(pr,autoalias) 1
set vTcl(pr,relative_placement) 1
set vTcl(mode) Relative
set vTcl(project_theme) default



proc vTclWindow.top1 {base} {
    global vTcl
    if {$base == ""} {
        set base .top1
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    set target $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -menu $top.m50 -background #d9d9d9 -highlightbackground #d9d9d9 \
        -highlightcolor #000000 
    wm focusmodel $top passive
    wm geometry $top 813x650+463+191
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1366 746
    wm minsize $top 120 1
    wm overrideredirect $top 0
    wm resizable $top 0 0
    wm deiconify $top
    set toptitle "Toplevel 0"
    wm title $top $toptitle
    namespace eval ::widgets::${top}::ClassOption {}
    set ::widgets::${top}::ClassOption(-toptitle) $toptitle
    vTcl:DefineAlias "$top" "Toplevel1" vTcl:Toplevel:WidgetProc "" 1
    set vTcl(real_top) {}
    menu "$top.m50" \
        -activebackground #d9d9d9 -activeforeground black \
        -font "-family {Segoe UI} -size 9" -tearoff 0 
    button "$top.but65" \
        -activebackground #d9d9d9 -activeforeground black -background #d9d9d9 \
        -command "lambda: moven(5)" -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 9" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -text "-" 
    vTcl:DefineAlias "$top.but65" "Button5_1" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $top.but65
    button "$top.but66" \
        -activebackground #d9d9d9 -activeforeground black -background #d9d9d9 \
        -command "lambda: moven(6)" -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 9" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -text "-" 
    vTcl:DefineAlias "$top.but66" "Button6_1" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $top.but66
    button "$top.but48" \
        -activebackground #d9d9d9 -activeforeground black -background #d9d9d9 \
        -command "lambda: moven(1)" -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 9" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -text "-" 
    vTcl:DefineAlias "$top.but48" "Button1_1" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $top.but48
    button "$top.but67" \
        -activebackground #d9d9d9 -activeforeground black -background #d9d9d9 \
        -command "lambda: moven(7)" -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 9" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -text "-" 
    vTcl:DefineAlias "$top.but67" "Button7_1" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $top.but67
    button "$top.but55" \
        -activebackground #d9d9d9 -activeforeground black -background #d9d9d9 \
        -command "lambda: movep(4)" -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 9" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -text "+" 
    vTcl:DefineAlias "$top.but55" "Button4" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $top.but55
    button "$top.but59" \
        -activebackground #d9d9d9 -activeforeground black -background #d9d9d9 \
        -command "lambda: movep(7)" -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 9" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -text "+" 
    vTcl:DefineAlias "$top.but59" "Button7" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $top.but59
    button "$top.but60" \
        -activebackground #d9d9d9 -activeforeground black -background #d9d9d9 \
        -command "lambda: movep(8)" -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 9" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -text "+" 
    vTcl:DefineAlias "$top.but60" "Button8" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $top.but60
    label "$top.lab72" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #d9d9d9 -compound left -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 9" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -text "Motor 3" 
    vTcl:DefineAlias "$top.lab72" "Label1_1_1" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $top.lab72
    button "$top.but63" \
        -activebackground #d9d9d9 -activeforeground black -background #d9d9d9 \
        -command "lambda: moven(3)" -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 9" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -text "-" 
    vTcl:DefineAlias "$top.but63" "Button3_1" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $top.but63
    button "$top.but54" \
        -activebackground #d9d9d9 -activeforeground black -background #d9d9d9 \
        -command "lambda: movep(3)" -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 9" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -text "+" 
    vTcl:DefineAlias "$top.but54" "Button3" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $top.but54
    button "$top.but69" \
        -activebackground #d9d9d9 -activeforeground black -background #d9d9d9 \
        -command "lambda: moven(9)" -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 9" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -text "-" 
    vTcl:DefineAlias "$top.but69" "Button9_1" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $top.but69
    button "$top.but62" \
        -activebackground #d9d9d9 -activeforeground black -background #d9d9d9 \
        -command "lambda: moven(2)" -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 9" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -text "-" 
    vTcl:DefineAlias "$top.but62" "Button2_1" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $top.but62
    button "$top.but53" \
        -activebackground #d9d9d9 -activeforeground black -background #d9d9d9 \
        -command "lambda: movep(2)" -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 9" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -text "+" 
    vTcl:DefineAlias "$top.but53" "Button2" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $top.but53
    label "$top.lab73" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #d9d9d9 -compound left -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 9" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -text "Motor 4" 
    vTcl:DefineAlias "$top.lab73" "Label1_1_1_1" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $top.lab73
    label "$top.lab76" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #d9d9d9 -compound left -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 9" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -text "Motor 7" 
    vTcl:DefineAlias "$top.lab76" "Label1_1_1_1_1_1_1" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $top.lab76
    label "$top.lab80" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #d9d9d9 -compound left -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 9" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -text "Com:" 
    vTcl:DefineAlias "$top.lab80" "Label2" vTcl:WidgetProc "Toplevel1" 1
    entry "$top.ent81" \
        -background white -disabledforeground #a3a3a3 \
        -font "-family {Courier New} -size 10" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -insertbackground #000000 -selectbackground #d9d9d9 \
        -selectforeground black -show 45 -textvariable "45" -width 34 
    vTcl:DefineAlias "$top.ent81" "Entry2" vTcl:WidgetProc "Toplevel1" 1
    label "$top.lab75" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #d9d9d9 -compound left -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 9" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -text "Motor 6" 
    vTcl:DefineAlias "$top.lab75" "Label1_1_1_1_1_1" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $top.lab75
    label "$top.lab78" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #d9d9d9 -compound left -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 9" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -text "Motor 9" 
    vTcl:DefineAlias "$top.lab78" "Label1_1_1_1_1_1_1_1_1" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $top.lab78
    button "$top.but64" \
        -activebackground #d9d9d9 -activeforeground black -background #d9d9d9 \
        -command "lambda: moven(4)" -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 9" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -text "-" 
    vTcl:DefineAlias "$top.but64" "Button4_1" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $top.but64
    button "$top.but56" \
        -activebackground #d9d9d9 -activeforeground black -background #d9d9d9 \
        -command "lambda: movep(5)" -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 9" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -text "+" 
    vTcl:DefineAlias "$top.but56" "Button5" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $top.but56
    button "$top.but57" \
        -activebackground #d9d9d9 -activeforeground black -background #d9d9d9 \
        -command "lambda: movep(6)" -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 9" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -text "+" 
    vTcl:DefineAlias "$top.but57" "Button6" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $top.but57
    button "$top.but61" \
        -activebackground #d9d9d9 -activeforeground black -background #d9d9d9 \
        -command "lambda: movep(9)" -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 9" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -text "+" 
    vTcl:DefineAlias "$top.but61" "Button9" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $top.but61
    entry "$top.ent79" \
        -background white -disabledforeground #a3a3a3 \
        -font "-family {Courier New} -size 10" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -insertbackground #000000 -selectbackground #d9d9d9 \
        -selectforeground black -width 24 
    vTcl:DefineAlias "$top.ent79" "Entry1" vTcl:WidgetProc "Toplevel1" 1
    button "$top.but49" \
        -activebackground #d9d9d9 -activeforeground black -background #d9d9d9 \
        -disabledforeground #a3a3a3 -font "-family {Segoe UI} -size 9" \
        -foreground #000000 -highlightbackground #d9d9d9 \
        -highlightcolor #000000 -text "Connect" 
    vTcl:DefineAlias "$top.but49" "Button10" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $top.but49
    button "$top.but68" \
        -activebackground #d9d9d9 -activeforeground black -background #d9d9d9 \
        -command "lambda: moven(8)" -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 9" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -text "-" 
    vTcl:DefineAlias "$top.but68" "Button8_1" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $top.but68
    label "$top.lab77" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #d9d9d9 -compound left -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 9" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -text "Motor 8" 
    vTcl:DefineAlias "$top.lab77" "Label1_1_1_1_1_1_1_1" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $top.lab77
    label "$top.lab74" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #d9d9d9 -compound left -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 9" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -text "Motor 5" 
    vTcl:DefineAlias "$top.lab74" "Label1_1_1_1_1" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $top.lab74
    label "$top.lab82" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #d9d9d9 -compound left -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 9" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -text "Angle" 
    vTcl:DefineAlias "$top.lab82" "Label3" vTcl:WidgetProc "Toplevel1" 1
    label "$top.lab70" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #d9d9d9 -compound left -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 9" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -text "Motor 2" 
    vTcl:DefineAlias "$top.lab70" "Label1_1" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $top.lab70
    label "$top.lab49" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #d9d9d9 -compound left -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 9" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -text "Motor 1" 
    vTcl:DefineAlias "$top.lab49" "Label1" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $top.lab49
    button "$top.but47" \
        -activebackground #d9d9d9 -activeforeground black -background #d9d9d9 \
        -command "lambda: movep(1)" -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 9" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -text "+" 
    vTcl:DefineAlias "$top.but47" "Button1" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $top.but47
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.but65 \
        -in $top -x 0 -relx 0.445 -y 0 -rely 0.154 -width 20 -relwidth 0 \
        -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $top.but66 \
        -in $top -x 0 -relx 0.644 -y 0 -rely 0.154 -width 20 -relwidth 0 \
        -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $top.but48 \
        -in $top -x 0 -relx 0.234 -y 0 -rely 0.077 -width 20 -relwidth 0 \
        -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $top.but67 \
        -in $top -x 0 -relx 0.234 -y 0 -rely 0.231 -width 20 -relwidth 0 \
        -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $top.but55 \
        -in $top -x 0 -relx 0.187 -y 0 -rely 0.154 -width 20 -relwidth 0 \
        -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $top.but59 \
        -in $top -x 0 -relx 0.187 -y 0 -rely 0.231 -width 20 -relwidth 0 \
        -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $top.but60 \
        -in $top -x 0 -relx 0.399 -y 0 -rely 0.231 -width 20 -relwidth 0 \
        -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $top.lab72 \
        -in $top -x 0 -relx 0.515 -y 0 -rely 0.077 -width 0 -relwidth 0.075 \
        -height 0 -relheight 0.031 -anchor nw -bordermode ignore 
    place $top.but63 \
        -in $top -x 0 -relx 0.645 -y 0 -rely 0.077 -width 20 -relwidth 0 \
        -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $top.but54 \
        -in $top -x 0 -relx 0.597 -y 0 -rely 0.077 -width 20 -relwidth 0 \
        -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $top.but69 \
        -in $top -x 0 -relx 0.645 -y 0 -rely 0.231 -width 20 -relwidth 0 \
        -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $top.but62 \
        -in $top -x 0 -relx 0.445 -y 0 -rely 0.077 -width 20 -relwidth 0 \
        -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $top.but53 \
        -in $top -x 0 -relx 0.399 -y 0 -rely 0.077 -width 20 -relwidth 0 \
        -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $top.lab73 \
        -in $top -x 0 -relx 0.105 -y 0 -rely 0.154 -width 0 -relwidth 0.075 \
        -height 0 -relheight 0.031 -anchor nw -bordermode ignore 
    place $top.lab76 \
        -in $top -x 0 -relx 0.105 -y 0 -rely 0.231 -width 0 -relwidth 0.075 \
        -height 0 -relheight 0.031 -anchor nw -bordermode ignore 
    place $top.lab80 \
        -in $top -x 0 -relx 0.7 -y 0 -rely 0.023 -width 0 -relwidth 0.057 \
        -height 0 -relheight 0.048 -anchor nw -bordermode ignore 
    place $top.ent81 \
        -in $top -x 0 -relx 0.192 -y 0 -rely 0.024 -width 34 -relwidth 0 \
        -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $top.lab75 \
        -in $top -x 0 -relx 0.515 -y 0 -rely 0.154 -width 0 -relwidth 0.075 \
        -height 0 -relheight 0.031 -anchor nw -bordermode ignore 
    place $top.lab78 \
        -in $top -x 0 -relx 0.515 -y 0 -rely 0.231 -width 0 -relwidth 0.075 \
        -height 0 -relheight 0.031 -anchor nw -bordermode ignore 
    place $top.but64 \
        -in $top -x 0 -relx 0.234 -y 0 -rely 0.154 -width 20 -relwidth 0 \
        -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $top.but56 \
        -in $top -x 0 -relx 0.398 -y 0 -rely 0.154 -width 20 -relwidth 0 \
        -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $top.but57 \
        -in $top -x 0 -relx 0.597 -y 0 -rely 0.154 -width 20 -relwidth 0 \
        -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $top.but61 \
        -in $top -x 0 -relx 0.597 -y 0 -rely 0.231 -width 20 -relwidth 0 \
        -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $top.ent79 \
        -in $top -x 0 -relx 0.75 -y 0 -rely 0.031 -width 24 -relwidth 0 \
        -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $top.but49 \
        -in $top -x 0 -relx 0.8 -y 0 -rely 0.031 -width 47 -relwidth 0 \
        -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $top.but68 \
        -in $top -x 0 -relx 0.445 -y 0 -rely 0.231 -width 20 -relwidth 0 \
        -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $top.lab77 \
        -in $top -x 0 -relx 0.316 -y 0 -rely 0.231 -width 0 -relwidth 0.075 \
        -height 0 -relheight 0.031 -anchor nw -bordermode ignore 
    place $top.lab74 \
        -in $top -x 0 -relx 0.316 -y 0 -rely 0.154 -width 0 -relwidth 0.075 \
        -height 0 -relheight 0.031 -anchor nw -bordermode ignore 
    place $top.lab82 \
        -in $top -x 0 -relx 0.112 -y 0 -rely 0.024 -width 0 -relwidth 0.054 \
        -height 0 -relheight 0.05 -anchor nw -bordermode ignore 
    place $top.lab70 \
        -in $top -x 0 -relx 0.316 -y 0 -rely 0.077 -width 0 -relwidth 0.075 \
        -height 0 -relheight 0.031 -anchor nw -bordermode ignore 
    place $top.lab49 \
        -in $top -x 0 -relx 0.105 -y 0 -rely 0.077 -width 0 -relwidth 0.075 \
        -height 0 -relheight 0.031 -anchor nw -bordermode ignore 
    place $top.but47 \
        -in $top -x 0 -relx 0.187 -y 0 -rely 0.077 -width 20 -relwidth 0 \
        -height 20 -relheight 0 -anchor nw -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

proc 36 {args} {return 1}


Window show .
set btop1 ""
if {$vTcl(borrow)} {
    set btop1 .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop1 $vTcl(tops)] != -1} {
        set btop1 .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop1
Window show .top1 $btop1
if {$vTcl(borrow)} {
    $btop1 configure -background plum
}

