#############################################################################
# Generated by PAGE version 8.0
#  in conjunction with Tcl version 8.6
#  Sep 30, 2024 11:06:25 PM CEST  platform: Windows NT
set vTcl(timestamp) ""
if {![info exists vTcl(borrow)]} {
    ::vTcl::MessageBox -title Error -message  "You must open project files from within PAGE."
    exit}


set vTcl(actual_gui_font_dft_desc)  TkDefaultFont
set vTcl(actual_gui_font_dft_name)  TkDefaultFont
set vTcl(actual_gui_font_text_desc)  TkTextFont
set vTcl(actual_gui_font_text_name)  TkTextFont
set vTcl(actual_gui_font_fixed_desc)  TkFixedFont
set vTcl(actual_gui_font_fixed_name)  TkFixedFont
set vTcl(actual_gui_font_menu_desc)  TkMenuFont
set vTcl(actual_gui_font_menu_name)  TkMenuFont
set vTcl(actual_gui_font_tooltip_desc)  TkDefaultFont
set vTcl(actual_gui_font_tooltip_name)  TkDefaultFont
set vTcl(actual_gui_font_treeview_desc)  TkDefaultFont
set vTcl(actual_gui_font_treeview_name)  TkDefaultFont
########################################### 
set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) gray40
set vTcl(analog_color_p) #c3c3c3
set vTcl(analog_color_m) beige
set vTcl(tabfg1) black
set vTcl(tabfg2) white
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(actual_gui_menu_active_fg)  #000000
########################################### 
set vTcl(pr,autoalias) 1
set vTcl(pr,relative_placement) 1
set vTcl(mode) Relative
set vTcl(project_theme) default



proc vTclWindow.top1 {base} {
    global vTcl
    if {$base == ""} {
        set base .top1
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    set target $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -menu $top.m50 -background #d9d9d9 -highlightbackground #d9d9d9 \
        -highlightcolor #000000 
    wm focusmodel $top passive
    wm geometry $top 813x650+450+188
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1366 746
    wm minsize $top 120 1
    wm overrideredirect $top 0
    wm resizable $top 0 0
    wm deiconify $top
    set toptitle "Toplevel 0"
    wm title $top $toptitle
    namespace eval ::widgets::${top}::ClassOption {}
    set ::widgets::${top}::ClassOption(-toptitle) $toptitle
    vTcl:DefineAlias "$top" "Toplevel1" vTcl:Toplevel:WidgetProc "" 1
    set vTcl(real_top) {}
    vTcl:copy_lock $top
    menu "$top.m50" \
        -activebackground #d9d9d9 -activeforeground black \
        -font "-family {Segoe UI} -size 9" -tearoff 0 
    label "$top.lab80" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #d9d9d9 -compound left -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 9" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -text "Com:" 
    vTcl:DefineAlias "$top.lab80" "Label2" vTcl:WidgetProc "Toplevel1" 1
    label "$top.lab82" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #d9d9d9 -compound left -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 9" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -text "Angle" 
    vTcl:DefineAlias "$top.lab82" "Label3" vTcl:WidgetProc "Toplevel1" 1
    entry "$top.ent79" \
        -background white -disabledforeground #a3a3a3 \
        -font "-family {Courier New} -size 10" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -insertbackground #000000 -selectbackground #d9d9d9 \
        -selectforeground black -textvariable "com" -width 24 
    vTcl:DefineAlias "$top.ent79" "Entry1" vTcl:WidgetProc "Toplevel1" 1
    entry "$top.ent81" \
        -background white -disabledforeground #a3a3a3 \
        -font "-family {Courier New} -size 10" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -insertbackground #000000 -selectbackground #d9d9d9 \
        -selectforeground black -textvariable "angle" -width 34 
    vTcl:DefineAlias "$top.ent81" "Entry2" vTcl:WidgetProc "Toplevel1" 1
    label "$top.lab73" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #d9d9d9 -compound left -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 9" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -text "Motor 4" 
    vTcl:DefineAlias "$top.lab73" "Label1_1_1_1" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $top.lab73
    label "$top.lab49" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #d9d9d9 -compound left -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 9" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -text "Motor 1" 
    vTcl:DefineAlias "$top.lab49" "Label1" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $top.lab49
    label "$top.lab50" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #d9d9d9 -compound left -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 9" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -text "Motor 13" 
    vTcl:DefineAlias "$top.lab50" "Label4" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $top.lab50
    label "$top.lab52" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #d9d9d9 -compound left -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 9" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -text "Motor 19" 
    vTcl:DefineAlias "$top.lab52" "Label4_1_1" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $top.lab52
    label "$top.lab53" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #d9d9d9 -compound left -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 9" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -text "Motor 22" 
    vTcl:DefineAlias "$top.lab53" "Label4_1_1_1" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $top.lab53
    label "$top.lab54" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #d9d9d9 -compound left -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 9" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -text "Motor 25" 
    vTcl:DefineAlias "$top.lab54" "Label4_1_1_1_1" vTcl:WidgetProc "Toplevel1" 1
    label "$top.lab55" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #d9d9d9 -compound left -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 9" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -text "Motor 28" 
    vTcl:DefineAlias "$top.lab55" "Label4_1_1_1_1_1" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $top.lab55
    label "$top.lab56" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #d9d9d9 -compound left -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 9" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -text "Motor 31" 
    vTcl:DefineAlias "$top.lab56" "Label4_1_1_1_1_1_1" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $top.lab56
    label "$top.lab57" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #d9d9d9 -compound left -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 9" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -text "Motor 34" 
    vTcl:DefineAlias "$top.lab57" "Label4_1_1_1_1_1_1_1" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $top.lab57
    button "$top.but49" \
        -activebackground #d9d9d9 -activeforeground black -background #d9d9d9 \
        -command "connect" -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 9" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -text "Connect" 
    vTcl:DefineAlias "$top.but49" "ButtonConnect" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $top.but49
    label "$top.lab76" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #d9d9d9 -compound left -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 9" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -text "Motor 7" 
    vTcl:DefineAlias "$top.lab76" "Label1_1_1_1_1_1_1" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $top.lab76
    label "$top.lab77" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #d9d9d9 -compound left -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 9" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -text "Motor 8" 
    vTcl:DefineAlias "$top.lab77" "Label1_1_1_1_1_1_1_1" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $top.lab77
    label "$top.lab74" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #d9d9d9 -compound left -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 9" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -text "Motor 5" 
    vTcl:DefineAlias "$top.lab74" "Label1_1_1_1_1" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $top.lab74
    label "$top.lab62" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #d9d9d9 -compound left -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 9" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -text "Motor 17" 
    vTcl:DefineAlias "$top.lab62" "Label1_1_1_1_1_1_1_1_2_1_1" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $top.lab62
    label "$top.lab63" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #d9d9d9 -compound left -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 9" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -text "Motor 20" 
    vTcl:DefineAlias "$top.lab63" "Label1_1_1_1_1_1_1_1_2_1_1_1" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $top.lab63
    label "$top.lab64" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #d9d9d9 -compound left -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 9" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -text "Motor 23" 
    vTcl:DefineAlias "$top.lab64" "Label1_1_1_1_1_1_1_1_2_1_1_1_1" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $top.lab64
    label "$top.lab65" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #d9d9d9 -compound left -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 9" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -text "Motor 26" 
    vTcl:DefineAlias "$top.lab65" "Label1_1_1_1_1_1_1_1_2_1_1_1_1_1" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $top.lab65
    label "$top.lab66" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #d9d9d9 -compound left -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 9" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -text "Motor 29" 
    vTcl:DefineAlias "$top.lab66" "Label1_1_1_1_1_1_1_1_2_1_1_1_1_1_1" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $top.lab66
    label "$top.lab67" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #d9d9d9 -compound left -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 9" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -text "Motor 32" 
    vTcl:DefineAlias "$top.lab67" "Label1_1_1_1_1_1_1_1_2_1_1_1_1_1_1_1" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $top.lab67
    label "$top.lab68" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #d9d9d9 -compound left -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 9" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -text "Motor 35" 
    vTcl:DefineAlias "$top.lab68" "Label1_1_1_1_1_1_1_1_2_1_1_1_1_1_1_1_1" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $top.lab68
    button "$top.but56" \
        -activebackground #d9d9d9 -activeforeground black -background #d9d9d9 \
        -command "lambda: movep(5)" -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 9" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -text "+" 
    vTcl:DefineAlias "$top.but56" "Button5" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $top.but56
    label "$top.lab61" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #d9d9d9 -compound left -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 9" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -text "Motor 14" 
    vTcl:DefineAlias "$top.lab61" "Label1_1_1_1_1_1_1_1_2_1" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $top.lab61
    label "$top.lab51" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #d9d9d9 -compound left -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 9" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -text "Motor 16" 
    vTcl:DefineAlias "$top.lab51" "Label4_1" vTcl:WidgetProc "Toplevel1" 1
    label "$top.lab47" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #d9d9d9 -compound left -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 9" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -text "Motor 10" 
    vTcl:DefineAlias "$top.lab47" "Label1_1_1_1_1_1_1_2" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $top.lab47
    label "$top.lab59" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #d9d9d9 -compound left -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 9" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -text "Motor 11" 
    vTcl:DefineAlias "$top.lab59" "Label1_1_1_1_1_1_1_1_2" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $top.lab59
    label "$top.lab78" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #d9d9d9 -compound left -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 9" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -text "Motor 9" 
    vTcl:DefineAlias "$top.lab78" "Label1_1_1_1_1_1_1_1_1" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $top.lab78
    label "$top.lab75" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #d9d9d9 -compound left -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 9" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -text "Motor 6" 
    vTcl:DefineAlias "$top.lab75" "Label1_1_1_1_1_1" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $top.lab75
    label "$top.lab70" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #d9d9d9 -compound left -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 9" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -text "Motor 2" 
    vTcl:DefineAlias "$top.lab70" "Label1_1" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $top.lab70
    label "$top.lab72" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #d9d9d9 -compound left -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 9" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -text "Motor 3" 
    vTcl:DefineAlias "$top.lab72" "Label1_1_1" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $top.lab72
    button "$top.but57" \
        -activebackground #d9d9d9 -activeforeground black -background #d9d9d9 \
        -command "lambda: movep(6)" -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 9" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -text "+" 
    vTcl:DefineAlias "$top.but57" "Button6" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $top.but57
    label "$top.lab60" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #d9d9d9 -compound left -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 9" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -text "Motor 12" 
    vTcl:DefineAlias "$top.lab60" "Label1_1_1_1_1_1_1_1_1_1" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $top.lab60
    label "$top.lab69" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #d9d9d9 -compound left -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 9" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -text "Motor 15" 
    vTcl:DefineAlias "$top.lab69" "Label1_1_1_1_1_1_1_1_1_1_1" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $top.lab69
    label "$top.lab79" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #d9d9d9 -compound left -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 9" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -text "Motor 21" 
    vTcl:DefineAlias "$top.lab79" "Label1_1_1_1_1_1_1_1_1_1_1_1_1" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $top.lab79
    label "$top.lab81" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #d9d9d9 -compound left -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 9" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -text "Motor 24" 
    vTcl:DefineAlias "$top.lab81" "Label1_1_1_1_1_1_1_1_1_1_1_1_1_1" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $top.lab81
    label "$top.lab83" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #d9d9d9 -compound left -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 9" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -text "Motor 27" 
    vTcl:DefineAlias "$top.lab83" "Label1_1_1_1_1_1_1_1_1_1_1_1_1_1_1" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $top.lab83
    label "$top.lab84" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #d9d9d9 -compound left -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 9" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -text "Motor 30" 
    vTcl:DefineAlias "$top.lab84" "Label1_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $top.lab84
    label "$top.lab86" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #d9d9d9 -compound left -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 9" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -text "Motor 36" 
    vTcl:DefineAlias "$top.lab86" "Label1_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $top.lab86
    button "$top.but47" \
        -activebackground #d9d9d9 -activeforeground black -background #d9d9d9 \
        -command "lambda: movep(1)" -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 9" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -text "+" 
    vTcl:DefineAlias "$top.but47" "Button1" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $top.but47
    label "$top.lab71" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #d9d9d9 -compound left -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 9" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -text "Motor 18" 
    vTcl:DefineAlias "$top.lab71" "Label1_1_1_1_1_1_1_1_1_1_1_1" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $top.lab71
    button "$top.but48" \
        -activebackground #d9d9d9 -activeforeground black -background #d9d9d9 \
        -command "lambda: moven(1)" -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 9" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -text "-" 
    vTcl:DefineAlias "$top.but48" "Button1_1" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $top.but48
    button "$top.but64" \
        -activebackground #d9d9d9 -activeforeground black -background #d9d9d9 \
        -command "lambda: moven(4)" -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 9" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -text "-" 
    vTcl:DefineAlias "$top.but64" "Button4_1" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $top.but64
    button "$top.but55" \
        -activebackground #d9d9d9 -activeforeground black -background #d9d9d9 \
        -command "lambda: movep(4)" -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 9" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -text "+" 
    vTcl:DefineAlias "$top.but55" "Button4" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $top.but55
    button "$top.but62" \
        -activebackground #d9d9d9 -activeforeground black -background #d9d9d9 \
        -command "lambda: moven(2)" -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 9" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -text "-" 
    vTcl:DefineAlias "$top.but62" "Button2_1" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $top.but62
    button "$top.but53" \
        -activebackground #d9d9d9 -activeforeground black -background #d9d9d9 \
        -command "lambda: movep(2)" -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 9" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -text "+" 
    vTcl:DefineAlias "$top.but53" "Button2" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $top.but53
    button "$top.but65" \
        -activebackground #d9d9d9 -activeforeground black -background #d9d9d9 \
        -command "lambda: moven(5)" -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 9" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -text "-" 
    vTcl:DefineAlias "$top.but65" "Button5_1" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $top.but65
    button "$top.but54" \
        -activebackground #d9d9d9 -activeforeground black -background #d9d9d9 \
        -command "lambda: movep(3)" -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 9" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -text "+" 
    vTcl:DefineAlias "$top.but54" "Button3" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $top.but54
    button "$top.but63" \
        -activebackground #d9d9d9 -activeforeground black -background #d9d9d9 \
        -command "lambda: moven(3)" -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 9" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -text "-" 
    vTcl:DefineAlias "$top.but63" "Button3_1" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $top.but63
    button "$top.but66" \
        -activebackground #d9d9d9 -activeforeground black -background #d9d9d9 \
        -command "lambda: moven(6)" -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 9" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -text "-" 
    vTcl:DefineAlias "$top.but66" "Button6_1" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $top.but66
    label "$top.lab85" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #d9d9d9 -compound left -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 9" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -text "Motor 33" 
    vTcl:DefineAlias "$top.lab85" "Label1_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1_1" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $top.lab85
    button "$top.but59" \
        -activebackground #d9d9d9 -activeforeground black -background #d9d9d9 \
        -command "lambda: movep(7)" -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 9" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -text "+" 
    vTcl:DefineAlias "$top.but59" "Button7" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $top.but59
    button "$top.but51" \
        -activebackground #d9d9d9 -activeforeground black -background #d9d9d9 \
        -command "lambda: movep(10)" -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 9" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -text "+" 
    vTcl:DefineAlias "$top.but51" "Button10" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $top.but51
    button "$top.but52" \
        -activebackground #d9d9d9 -activeforeground black -background #d9d9d9 \
        -command "lambda: movep(13)" -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 9" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -text "+" 
    vTcl:DefineAlias "$top.but52" "Button13" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $top.but52
    button "$top.but58" \
        -activebackground #d9d9d9 -activeforeground black -background #d9d9d9 \
        -command "lambda: movep(16)" -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 9" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -text "+" 
    vTcl:DefineAlias "$top.but58" "Button16" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $top.but58
    button "$top.but70" \
        -activebackground #d9d9d9 -activeforeground black -background #d9d9d9 \
        -command "lambda: movep(19)" -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 9" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -text "+" 
    vTcl:DefineAlias "$top.but70" "Button19" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $top.but70
    button "$top.but71" \
        -activebackground #d9d9d9 -activeforeground black -background #d9d9d9 \
        -command "lambda: movep(22)" -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 9" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -text "+" 
    vTcl:DefineAlias "$top.but71" "Button22" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $top.but71
    button "$top.but72" \
        -activebackground #d9d9d9 -activeforeground black -background #d9d9d9 \
        -command "lambda: movep(25)" -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 9" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -text "+" 
    vTcl:DefineAlias "$top.but72" "Button25" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $top.but72
    button "$top.but73" \
        -activebackground #d9d9d9 -activeforeground black -background #d9d9d9 \
        -command "lambda: movep(28)" -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 9" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -text "+" 
    vTcl:DefineAlias "$top.but73" "Button28" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $top.but73
    button "$top.but74" \
        -activebackground #d9d9d9 -activeforeground black -background #d9d9d9 \
        -command "lambda: movep(31)" -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 9" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -text "+" 
    vTcl:DefineAlias "$top.but74" "Button31" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $top.but74
    button "$top.but75" \
        -activebackground #d9d9d9 -activeforeground black -background #d9d9d9 \
        -command "lambda: movep(34)" -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 9" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -text "+" 
    vTcl:DefineAlias "$top.but75" "Button34" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $top.but75
    button "$top.but67" \
        -activebackground #d9d9d9 -activeforeground black -background #d9d9d9 \
        -command "lambda: moven(7)" -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 9" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -text "-" 
    vTcl:DefineAlias "$top.but67" "Button7_1" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $top.but67
    button "$top.but93" \
        -activebackground #d9d9d9 -activeforeground black -background #d9d9d9 \
        -command "lambda: movep(7)" -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 9" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -text "-" 
    vTcl:DefineAlias "$top.but93" "Button10_1" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $top.but93
    button "$top.but94" \
        -activebackground #d9d9d9 -activeforeground black -background #d9d9d9 \
        -command "lambda: moven(13)" -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 9" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -text "-" 
    vTcl:DefineAlias "$top.but94" "Button13_1" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $top.but94
    button "$top.but95" \
        -activebackground #d9d9d9 -activeforeground black -background #d9d9d9 \
        -command "lambda: moven(16)" -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 9" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -text "-" 
    vTcl:DefineAlias "$top.but95" "Button16_1" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $top.but95
    button "$top.but96" \
        -activebackground #d9d9d9 -activeforeground black -background #d9d9d9 \
        -command "lambda: moven(19)" -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 9" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -text "-" 
    vTcl:DefineAlias "$top.but96" "Button19_1" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $top.but96
    button "$top.but97" \
        -activebackground #d9d9d9 -activeforeground black -background #d9d9d9 \
        -command "lambda: moven(22)" -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 9" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -text "-" 
    vTcl:DefineAlias "$top.but97" "Button22_1" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $top.but97
    button "$top.but98" \
        -activebackground #d9d9d9 -activeforeground black -background #d9d9d9 \
        -command "lambda: moven(25)" -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 9" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -text "-" 
    vTcl:DefineAlias "$top.but98" "Button25_1" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $top.but98
    button "$top.but99" \
        -activebackground #d9d9d9 -activeforeground black -background #d9d9d9 \
        -command "lambda: moven(28)" -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 9" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -text "-" 
    vTcl:DefineAlias "$top.but99" "Button28_1" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $top.but99
    button "$top.but100" \
        -activebackground #d9d9d9 -activeforeground black -background #d9d9d9 \
        -command "lambda: moven(31)" -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 9" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -text "-" 
    vTcl:DefineAlias "$top.but100" "Button31_1" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $top.but100
    button "$top.but101" \
        -activebackground #d9d9d9 -activeforeground black -background #d9d9d9 \
        -command "lambda: moven(34)" -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 9" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -text "-" 
    vTcl:DefineAlias "$top.but101" "Button34_1" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $top.but101
    button "$top.but60" \
        -activebackground #d9d9d9 -activeforeground black -background #d9d9d9 \
        -command "lambda: movep(8)" -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 9" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -text "+" 
    vTcl:DefineAlias "$top.but60" "Button8" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $top.but60
    button "$top.but50" \
        -activebackground #d9d9d9 -activeforeground black -background #d9d9d9 \
        -command "lambda: movep(11)" -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 9" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -text "+" 
    vTcl:DefineAlias "$top.but50" "Button11" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $top.but50
    button "$top.but76" \
        -activebackground #d9d9d9 -activeforeground black -background #d9d9d9 \
        -command "lambda: movep(14)" -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 9" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -text "+" 
    vTcl:DefineAlias "$top.but76" "Button14" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $top.but76
    button "$top.but77" \
        -activebackground #d9d9d9 -activeforeground black -background #d9d9d9 \
        -command "lambda: movep(17)" -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 9" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -text "+" 
    vTcl:DefineAlias "$top.but77" "Button17" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $top.but77
    button "$top.but78" \
        -activebackground #d9d9d9 -activeforeground black -background #d9d9d9 \
        -command "lambda: movep(20)" -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 9" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -text "+" 
    vTcl:DefineAlias "$top.but78" "Button20" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $top.but78
    button "$top.but79" \
        -activebackground #d9d9d9 -activeforeground black -background #d9d9d9 \
        -command "lambda: movep(23)" -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 9" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -text "+" 
    vTcl:DefineAlias "$top.but79" "Button23" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $top.but79
    button "$top.but80" \
        -activebackground #d9d9d9 -activeforeground black -background #d9d9d9 \
        -command "lambda: movep(26)" -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 9" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -text "+" 
    vTcl:DefineAlias "$top.but80" "Button26" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $top.but80
    button "$top.but81" \
        -activebackground #d9d9d9 -activeforeground black -background #d9d9d9 \
        -command "lambda: movep(29)" -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 9" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -text "+" 
    vTcl:DefineAlias "$top.but81" "Button29" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $top.but81
    button "$top.but82" \
        -activebackground #d9d9d9 -activeforeground black -background #d9d9d9 \
        -command "lambda: movep(32)" -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 9" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -text "+" 
    vTcl:DefineAlias "$top.but82" "Button32" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $top.but82
    button "$top.but83" \
        -activebackground #d9d9d9 -activeforeground black -background #d9d9d9 \
        -command "lambda: movep(35)" -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 9" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -text "+" 
    vTcl:DefineAlias "$top.but83" "Button35" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $top.but83
    button "$top.but92" \
        -activebackground #d9d9d9 -activeforeground black -background #d9d9d9 \
        -command "lambda: movep(36)" -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 9" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -text "+" 
    vTcl:DefineAlias "$top.but92" "Button36" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $top.but92
    button "$top.but91" \
        -activebackground #d9d9d9 -activeforeground black -background #d9d9d9 \
        -command "lambda: movep(33)" -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 9" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -text "+" 
    vTcl:DefineAlias "$top.but91" "Button33" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $top.but91
    button "$top.but90" \
        -activebackground #d9d9d9 -activeforeground black -background #d9d9d9 \
        -command "lambda: movep(30)" -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 9" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -text "+" 
    vTcl:DefineAlias "$top.but90" "Button30" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $top.but90
    button "$top.but89" \
        -activebackground #d9d9d9 -activeforeground black -background #d9d9d9 \
        -command "lambda: movep(27)" -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 9" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -text "+" 
    vTcl:DefineAlias "$top.but89" "Button27" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $top.but89
    button "$top.but88" \
        -activebackground #d9d9d9 -activeforeground black -background #d9d9d9 \
        -command "lambda: movep(24)" -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 9" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -text "+" 
    vTcl:DefineAlias "$top.but88" "Button24" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $top.but88
    button "$top.but87" \
        -activebackground #d9d9d9 -activeforeground black -background #d9d9d9 \
        -command "lambda: movep(21)" -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 9" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -text "+" 
    vTcl:DefineAlias "$top.but87" "Button21" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $top.but87
    button "$top.but86" \
        -activebackground #d9d9d9 -activeforeground black -background #d9d9d9 \
        -command "lambda: movep(18)" -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 9" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -text "+" 
    vTcl:DefineAlias "$top.but86" "Button18" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $top.but86
    button "$top.but85" \
        -activebackground #d9d9d9 -activeforeground black -background #d9d9d9 \
        -command "lambda: movep(15)" -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 9" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -text "+" 
    vTcl:DefineAlias "$top.but85" "Button15" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $top.but85
    button "$top.but61" \
        -activebackground #d9d9d9 -activeforeground black -background #d9d9d9 \
        -command "lambda: movep(9)" -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 9" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -text "+" 
    vTcl:DefineAlias "$top.but61" "Button9" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $top.but61
    button "$top.but84" \
        -activebackground #d9d9d9 -activeforeground black -background #d9d9d9 \
        -command "lambda: movep(12)" -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 9" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -text "+" 
    vTcl:DefineAlias "$top.but84" "Button12" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $top.but84
    button "$top.but68" \
        -activebackground #d9d9d9 -activeforeground black -background #d9d9d9 \
        -command "lambda: moven(8)" -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 9" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -text "-" 
    vTcl:DefineAlias "$top.but68" "Button8_1" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $top.but68
    button "$top.but102" \
        -activebackground #d9d9d9 -activeforeground black -background #d9d9d9 \
        -command "lambda: moven(11)" -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 9" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -text "-" 
    vTcl:DefineAlias "$top.but102" "Button11_1" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $top.but102
    button "$top.but103" \
        -activebackground #d9d9d9 -activeforeground black -background #d9d9d9 \
        -command "lambda: moven(14)" -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 9" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -text "-" 
    vTcl:DefineAlias "$top.but103" "Button14_1" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $top.but103
    button "$top.but104" \
        -activebackground #d9d9d9 -activeforeground black -background #d9d9d9 \
        -command "lambda: moven(17)" -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 9" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -text "-" 
    vTcl:DefineAlias "$top.but104" "Button17_1" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $top.but104
    button "$top.but105" \
        -activebackground #d9d9d9 -activeforeground black -background #d9d9d9 \
        -command "lambda: moven(20)" -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 9" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -text "-" 
    vTcl:DefineAlias "$top.but105" "Button20_1" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $top.but105
    button "$top.but106" \
        -activebackground #d9d9d9 -activeforeground black -background #d9d9d9 \
        -command "lambda: moven(23)" -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 9" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -text "-" 
    vTcl:DefineAlias "$top.but106" "Button23_1" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $top.but106
    button "$top.but107" \
        -activebackground #d9d9d9 -activeforeground black -background #d9d9d9 \
        -command "lambda: moven(26)" -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 9" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -text "-" 
    vTcl:DefineAlias "$top.but107" "Button26_1" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $top.but107
    button "$top.but108" \
        -activebackground #d9d9d9 -activeforeground black -background #d9d9d9 \
        -command "lambda: moven(29)" -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 9" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -text "-" 
    vTcl:DefineAlias "$top.but108" "Button29_1" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $top.but108
    button "$top.but109" \
        -activebackground #d9d9d9 -activeforeground black -background #d9d9d9 \
        -command "lambda: moven(32)" -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 9" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -text "-" 
    vTcl:DefineAlias "$top.but109" "Button32_1" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $top.but109
    button "$top.but110" \
        -activebackground #d9d9d9 -activeforeground black -background #d9d9d9 \
        -command "lambda: moven(35)" -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 9" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -text "-" 
    vTcl:DefineAlias "$top.but110" "Button35_1" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $top.but110
    button "$top.but119" \
        -activebackground #d9d9d9 -activeforeground black -background #d9d9d9 \
        -command "lambda: moven(36)" -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 9" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -text "-" 
    vTcl:DefineAlias "$top.but119" "Button36_1" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $top.but119
    button "$top.but118" \
        -activebackground #d9d9d9 -activeforeground black -background #d9d9d9 \
        -command "lambda: moven(33)" -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 9" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -text "-" 
    vTcl:DefineAlias "$top.but118" "Button33_1" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $top.but118
    button "$top.but117" \
        -activebackground #d9d9d9 -activeforeground black -background #d9d9d9 \
        -command "lambda: moven(30)" -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 9" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -text "-" 
    vTcl:DefineAlias "$top.but117" "Button30_1" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $top.but117
    button "$top.but116" \
        -activebackground #d9d9d9 -activeforeground black -background #d9d9d9 \
        -command "lambda: moven(27)" -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 9" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -text "-" 
    vTcl:DefineAlias "$top.but116" "Button27_1" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $top.but116
    button "$top.but115" \
        -activebackground #d9d9d9 -activeforeground black -background #d9d9d9 \
        -command "lambda: moven(24)" -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 9" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -text "-" 
    vTcl:DefineAlias "$top.but115" "Button24_1" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $top.but115
    button "$top.but114" \
        -activebackground #d9d9d9 -activeforeground black -background #d9d9d9 \
        -command "lambda: moven(21)" -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 9" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -text "-" 
    vTcl:DefineAlias "$top.but114" "Button21_1" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $top.but114
    button "$top.but113" \
        -activebackground #d9d9d9 -activeforeground black -background #d9d9d9 \
        -command "lambda: moven(18)" -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 9" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -text "-" 
    vTcl:DefineAlias "$top.but113" "Button18_1" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $top.but113
    button "$top.but112" \
        -activebackground #d9d9d9 -activeforeground black -background #d9d9d9 \
        -command "lambda: moven(15)" -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 9" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -text "-" 
    vTcl:DefineAlias "$top.but112" "Button15_1" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $top.but112
    button "$top.but111" \
        -activebackground #d9d9d9 -activeforeground black -background #d9d9d9 \
        -command "lambda: moven(12)" -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 9" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -text "-" 
    vTcl:DefineAlias "$top.but111" "Button12_1" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $top.but111
    button "$top.but69" \
        -activebackground #d9d9d9 -activeforeground black -background #d9d9d9 \
        -command "lambda: moven(9)" -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 9" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -text "-" 
    vTcl:DefineAlias "$top.but69" "Button9_1" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $top.but69
    entry "$top.ent47" \
        -background white -disabledforeground #a3a3a3 \
        -font "-family {Courier New} -size 10" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -insertbackground #000000 -selectbackground #d9d9d9 \
        -selectforeground black -textvariable "com_scale1" -width 24 
    vTcl:DefineAlias "$top.ent47" "Entry3" vTcl:WidgetProc "Toplevel1" 1
    entry "$top.ent49" \
        -background white -disabledforeground #a3a3a3 \
        -font "-family {Courier New} -size 10" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -insertbackground #000000 -selectbackground #d9d9d9 \
        -selectforeground black -textvariable "com_scale3" -width 24 
    vTcl:DefineAlias "$top.ent49" "Entry3_1_1" vTcl:WidgetProc "Toplevel1" 1
    entry "$top.ent48" \
        -background white -disabledforeground #a3a3a3 \
        -font "-family {Courier New} -size 10" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -insertbackground #000000 -selectbackground #d9d9d9 \
        -selectforeground black -textvariable "com_scale2" -width 24 
    vTcl:DefineAlias "$top.ent48" "Entry3_1" vTcl:WidgetProc "Toplevel1" 1
    button "$top.but120" \
        -activebackground #d9d9d9 -activeforeground black -background #d9d9d9 \
        -command "connect_scales()" -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 9" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -text "Connect Scales" 
    vTcl:DefineAlias "$top.but120" "Button37" vTcl:WidgetProc "Toplevel1" 1
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.lab80 \
        -in $top -x 0 -relx 0.7 -y 0 -rely 0.023 -width 0 -relwidth 0.057 \
        -height 0 -relheight 0.048 -anchor nw -bordermode ignore 
    place $top.lab82 \
        -in $top -x 0 -relx 0.112 -y 0 -rely 0.024 -width 0 -relwidth 0.054 \
        -height 0 -relheight 0.05 -anchor nw -bordermode ignore 
    place $top.ent79 \
        -in $top -x 0 -relx 0.75 -y 0 -rely 0.031 -width 24 -relwidth 0 \
        -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $top.ent81 \
        -in $top -x 0 -relx 0.192 -y 0 -rely 0.024 -width 34 -relwidth 0 \
        -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $top.lab73 \
        -in $top -x 0 -relx 0.105 -y 0 -rely 0.154 -width 0 -relwidth 0.075 \
        -height 0 -relheight 0.031 -anchor nw -bordermode ignore 
    place $top.lab49 \
        -in $top -x 0 -relx 0.105 -y 0 -rely 0.077 -width 0 -relwidth 0.075 \
        -height 0 -relheight 0.031 -anchor nw -bordermode ignore 
    place $top.lab50 \
        -in $top -x 0 -relx 0.105 -y 0 -rely 0.385 -width 0 -relwidth 0.063 \
        -height 0 -relheight 0.032 -anchor nw -bordermode ignore 
    place $top.lab52 \
        -in $top -x 0 -relx 0.105 -y 0 -rely 0.538 -width 0 -relwidth 0.064 \
        -height 0 -relheight 0.032 -anchor nw -bordermode ignore 
    place $top.lab53 \
        -in $top -x 0 -relx 0.105 -y 0 -rely 0.615 -width 0 -relwidth 0.064 \
        -height 0 -relheight 0.032 -anchor nw -bordermode ignore 
    place $top.lab54 \
        -in $top -x 0 -relx 0.105 -y 0 -rely 0.692 -width 0 -relwidth 0.064 \
        -height 0 -relheight 0.032 -anchor nw -bordermode ignore 
    place $top.lab55 \
        -in $top -x 0 -relx 0.105 -y 0 -rely 0.769 -width 0 -relwidth 0.064 \
        -height 0 -relheight 0.032 -anchor nw -bordermode ignore 
    place $top.lab56 \
        -in $top -x 0 -relx 0.105 -y 0 -rely 0.846 -width 0 -relwidth 0.064 \
        -height 0 -relheight 0.032 -anchor nw -bordermode ignore 
    place $top.lab57 \
        -in $top -x 0 -relx 0.105 -y 0 -rely 0.923 -width 0 -relwidth 0.064 \
        -height 0 -relheight 0.032 -anchor nw -bordermode ignore 
    place $top.but49 \
        -in $top -x 0 -relx 0.8 -y 0 -rely 0.031 -width 47 -relwidth 0 \
        -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $top.lab76 \
        -in $top -x 0 -relx 0.105 -y 0 -rely 0.231 -width 0 -relwidth 0.075 \
        -height 0 -relheight 0.031 -anchor nw -bordermode ignore 
    place $top.lab77 \
        -in $top -x 0 -relx 0.32 -y 0 -rely 0.231 -width 0 -relwidth 0.075 \
        -height 0 -relheight 0.031 -anchor nw -bordermode ignore 
    place $top.lab74 \
        -in $top -x 0 -relx 0.32 -y 0 -rely 0.154 -width 0 -relwidth 0.075 \
        -height 0 -relheight 0.031 -anchor nw -bordermode ignore 
    place $top.lab62 \
        -in $top -x 0 -relx 0.32 -y 0 -rely 0.462 -width 0 -relwidth 0.075 \
        -height 0 -relheight 0.031 -anchor nw -bordermode ignore 
    place $top.lab63 \
        -in $top -x 0 -relx 0.32 -y 0 -rely 0.538 -width 0 -relwidth 0.075 \
        -height 0 -relheight 0.031 -anchor nw -bordermode ignore 
    place $top.lab64 \
        -in $top -x 0 -relx 0.32 -y 0 -rely 0.615 -width 0 -relwidth 0.075 \
        -height 0 -relheight 0.031 -anchor nw -bordermode ignore 
    place $top.lab65 \
        -in $top -x 0 -relx 0.32 -y 0 -rely 0.692 -width 0 -relwidth 0.075 \
        -height 0 -relheight 0.031 -anchor nw -bordermode ignore 
    place $top.lab66 \
        -in $top -x 0 -relx 0.32 -y 0 -rely 0.769 -width 0 -relwidth 0.075 \
        -height 0 -relheight 0.031 -anchor nw -bordermode ignore 
    place $top.lab67 \
        -in $top -x 0 -relx 0.32 -y 0 -rely 0.846 -width 0 -relwidth 0.075 \
        -height 0 -relheight 0.031 -anchor nw -bordermode ignore 
    place $top.lab68 \
        -in $top -x 0 -relx 0.32 -y 0 -rely 0.923 -width 0 -relwidth 0.075 \
        -height 0 -relheight 0.031 -anchor nw -bordermode ignore 
    place $top.but56 \
        -in $top -x 0 -relx 0.4 -y 0 -rely 0.154 -width 20 -relwidth 0 \
        -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $top.lab61 \
        -in $top -x 0 -relx 0.32 -y 0 -rely 0.385 -width 0 -relwidth 0.075 \
        -height 0 -relheight 0.031 -anchor nw -bordermode ignore 
    place $top.lab51 \
        -in $top -x 0 -relx 0.105 -y 0 -rely 0.462 -width 0 -relwidth 0.064 \
        -height 0 -relheight 0.032 -anchor nw -bordermode ignore 
    place $top.lab47 \
        -in $top -x 0 -relx 0.105 -y 0 -rely 0.308 -width 0 -relwidth 0.075 \
        -height 0 -relheight 0.031 -anchor nw -bordermode ignore 
    place $top.lab59 \
        -in $top -x 0 -relx 0.32 -y 0 -rely 0.308 -width 0 -relwidth 0.075 \
        -height 0 -relheight 0.031 -anchor nw -bordermode ignore 
    place $top.lab78 \
        -in $top -x 0 -relx 0.535 -y 0 -rely 0.231 -width 0 -relwidth 0.075 \
        -height 0 -relheight 0.031 -anchor nw -bordermode ignore 
    place $top.lab75 \
        -in $top -x 0 -relx 0.535 -y 0 -rely 0.154 -width 0 -relwidth 0.075 \
        -height 0 -relheight 0.031 -anchor nw -bordermode ignore 
    place $top.lab70 \
        -in $top -x 0 -relx 0.32 -y 0 -rely 0.077 -width 0 -relwidth 0.075 \
        -height 0 -relheight 0.031 -anchor nw -bordermode ignore 
    place $top.lab72 \
        -in $top -x 0 -relx 0.535 -y 0 -rely 0.077 -width 0 -relwidth 0.075 \
        -height 0 -relheight 0.031 -anchor nw -bordermode ignore 
    place $top.but57 \
        -in $top -x 0 -relx 0.615 -y 0 -rely 0.154 -width 20 -relwidth 0 \
        -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $top.lab60 \
        -in $top -x 0 -relx 0.535 -y 0 -rely 0.308 -width 0 -relwidth 0.075 \
        -height 0 -relheight 0.031 -anchor nw -bordermode ignore 
    place $top.lab69 \
        -in $top -x 0 -relx 0.535 -y 0 -rely 0.385 -width 0 -relwidth 0.075 \
        -height 0 -relheight 0.031 -anchor nw -bordermode ignore 
    place $top.lab79 \
        -in $top -x 0 -relx 0.535 -y 0 -rely 0.538 -width 0 -relwidth 0.075 \
        -height 0 -relheight 0.031 -anchor nw -bordermode ignore 
    place $top.lab81 \
        -in $top -x 0 -relx 0.535 -y 0 -rely 0.615 -width 0 -relwidth 0.075 \
        -height 0 -relheight 0.031 -anchor nw -bordermode ignore 
    place $top.lab83 \
        -in $top -x 0 -relx 0.535 -y 0 -rely 0.692 -width 0 -relwidth 0.075 \
        -height 0 -relheight 0.031 -anchor nw -bordermode ignore 
    place $top.lab84 \
        -in $top -x 0 -relx 0.535 -y 0 -rely 0.769 -width 0 -relwidth 0.075 \
        -height 0 -relheight 0.031 -anchor nw -bordermode ignore 
    place $top.lab86 \
        -in $top -x 0 -relx 0.535 -y 0 -rely 0.923 -width 0 -relwidth 0.075 \
        -height 0 -relheight 0.031 -anchor nw -bordermode ignore 
    place $top.but47 \
        -in $top -x 0 -relx 0.185 -y 0 -rely 0.077 -width 20 -relwidth 0 \
        -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $top.lab71 \
        -in $top -x 0 -relx 0.535 -y 0 -rely 0.462 -width 0 -relwidth 0.075 \
        -height 0 -relheight 0.031 -anchor nw -bordermode ignore 
    place $top.but48 \
        -in $top -x 0 -relx 0.234 -y 0 -rely 0.077 -width 20 -relwidth 0 \
        -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $top.but64 \
        -in $top -x 0 -relx 0.234 -y 0 -rely 0.154 -width 20 -relwidth 0 \
        -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $top.but55 \
        -in $top -x 0 -relx 0.185 -y 0 -rely 0.154 -width 20 -relwidth 0 \
        -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $top.but62 \
        -in $top -x 0 -relx 0.449 -y 0 -rely 0.077 -width 20 -relwidth 0 \
        -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $top.but53 \
        -in $top -x 0 -relx 0.4 -y 0 -rely 0.077 -width 20 -relwidth 0 \
        -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $top.but65 \
        -in $top -x 0 -relx 0.449 -y 0 -rely 0.154 -width 20 -relwidth 0 \
        -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $top.but54 \
        -in $top -x 0 -relx 0.615 -y 0 -rely 0.077 -width 20 -relwidth 0 \
        -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $top.but63 \
        -in $top -x 0 -relx 0.664 -y 0 -rely 0.077 -width 20 -relwidth 0 \
        -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $top.but66 \
        -in $top -x 0 -relx 0.664 -y 0 -rely 0.154 -width 20 -relwidth 0 \
        -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $top.lab85 \
        -in $top -x 0 -relx 0.535 -y 0 -rely 0.846 -width 0 -relwidth 0.075 \
        -height 0 -relheight 0.031 -anchor nw -bordermode ignore 
    place $top.but59 \
        -in $top -x 0 -relx 0.185 -y 0 -rely 0.231 -width 20 -relwidth 0 \
        -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $top.but51 \
        -in $top -x 0 -relx 0.185 -y 0 -rely 0.308 -width 20 -relwidth 0 \
        -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $top.but52 \
        -in $top -x 0 -relx 0.185 -y 0 -rely 0.385 -width 20 -relwidth 0 \
        -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $top.but58 \
        -in $top -x 0 -relx 0.185 -y 0 -rely 0.462 -width 20 -relwidth 0 \
        -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $top.but70 \
        -in $top -x 0 -relx 0.185 -y 0 -rely 0.538 -width 20 -relwidth 0 \
        -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $top.but71 \
        -in $top -x 0 -relx 0.185 -y 0 -rely 0.615 -width 20 -relwidth 0 \
        -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $top.but72 \
        -in $top -x 0 -relx 0.185 -y 0 -rely 0.692 -width 20 -relwidth 0 \
        -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $top.but73 \
        -in $top -x 0 -relx 0.185 -y 0 -rely 0.769 -width 20 -relwidth 0 \
        -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $top.but74 \
        -in $top -x 0 -relx 0.185 -y 0 -rely 0.846 -width 20 -relwidth 0 \
        -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $top.but75 \
        -in $top -x 0 -relx 0.185 -y 0 -rely 0.923 -width 20 -relwidth 0 \
        -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $top.but67 \
        -in $top -x 0 -relx 0.234 -y 0 -rely 0.231 -width 20 -relwidth 0 \
        -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $top.but93 \
        -in $top -x 0 -relx 0.234 -y 0 -rely 0.308 -width 20 -relwidth 0 \
        -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $top.but94 \
        -in $top -x 0 -relx 0.234 -y 0 -rely 0.385 -width 20 -relwidth 0 \
        -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $top.but95 \
        -in $top -x 0 -relx 0.234 -y 0 -rely 0.462 -width 20 -relwidth 0 \
        -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $top.but96 \
        -in $top -x 0 -relx 0.234 -y 0 -rely 0.538 -width 20 -relwidth 0 \
        -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $top.but97 \
        -in $top -x 0 -relx 0.234 -y 0 -rely 0.615 -width 20 -relwidth 0 \
        -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $top.but98 \
        -in $top -x 0 -relx 0.234 -y 0 -rely 0.692 -width 20 -relwidth 0 \
        -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $top.but99 \
        -in $top -x 0 -relx 0.234 -y 0 -rely 0.769 -width 20 -relwidth 0 \
        -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $top.but100 \
        -in $top -x 0 -relx 0.234 -y 0 -rely 0.846 -width 20 -relwidth 0 \
        -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $top.but101 \
        -in $top -x 0 -relx 0.234 -y 0 -rely 0.923 -width 20 -relwidth 0 \
        -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $top.but60 \
        -in $top -x 0 -relx 0.399 -y 0 -rely 0.231 -width 20 -relwidth 0 \
        -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $top.but50 \
        -in $top -x 0 -relx 0.4 -y 0 -rely 0.308 -width 20 -relwidth 0 \
        -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $top.but76 \
        -in $top -x 0 -relx 0.4 -y 0 -rely 0.385 -width 20 -relwidth 0 \
        -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $top.but77 \
        -in $top -x 0 -relx 0.4 -y 0 -rely 0.462 -width 20 -relwidth 0 \
        -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $top.but78 \
        -in $top -x 0 -relx 0.4 -y 0 -rely 0.538 -width 20 -relwidth 0 \
        -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $top.but79 \
        -in $top -x 0 -relx 0.4 -y 0 -rely 0.615 -width 20 -relwidth 0 \
        -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $top.but80 \
        -in $top -x 0 -relx 0.4 -y 0 -rely 0.692 -width 20 -relwidth 0 \
        -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $top.but81 \
        -in $top -x 0 -relx 0.4 -y 0 -rely 0.769 -width 20 -relwidth 0 \
        -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $top.but82 \
        -in $top -x 0 -relx 0.4 -y 0 -rely 0.846 -width 20 -relwidth 0 \
        -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $top.but83 \
        -in $top -x 0 -relx 0.4 -y 0 -rely 0.923 -width 20 -relwidth 0 \
        -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $top.but92 \
        -in $top -x 0 -relx 0.615 -y 0 -rely 0.923 -width 20 -relwidth 0 \
        -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $top.but91 \
        -in $top -x 0 -relx 0.615 -y 0 -rely 0.846 -width 20 -relwidth 0 \
        -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $top.but90 \
        -in $top -x 0 -relx 0.615 -y 0 -rely 0.769 -width 20 -relwidth 0 \
        -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $top.but89 \
        -in $top -x 0 -relx 0.615 -y 0 -rely 0.692 -width 20 -relwidth 0 \
        -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $top.but88 \
        -in $top -x 0 -relx 0.615 -y 0 -rely 0.615 -width 20 -relwidth 0 \
        -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $top.but87 \
        -in $top -x 0 -relx 0.615 -y 0 -rely 0.538 -width 20 -relwidth 0 \
        -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $top.but86 \
        -in $top -x 0 -relx 0.615 -y 0 -rely 0.462 -width 20 -relwidth 0 \
        -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $top.but85 \
        -in $top -x 0 -relx 0.615 -y 0 -rely 0.385 -width 20 -relwidth 0 \
        -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $top.but61 \
        -in $top -x 0 -relx 0.615 -y 0 -rely 0.231 -width 20 -relwidth 0 \
        -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $top.but84 \
        -in $top -x 0 -relx 0.615 -y 0 -rely 0.308 -width 20 -relwidth 0 \
        -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $top.but68 \
        -in $top -x 0 -relx 0.449 -y 0 -rely 0.231 -width 20 -relwidth 0 \
        -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $top.but102 \
        -in $top -x 0 -relx 0.449 -y 0 -rely 0.308 -width 20 -relwidth 0 \
        -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $top.but103 \
        -in $top -x 0 -relx 0.449 -y 0 -rely 0.385 -width 20 -relwidth 0 \
        -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $top.but104 \
        -in $top -x 0 -relx 0.449 -y 0 -rely 0.462 -width 20 -relwidth 0 \
        -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $top.but105 \
        -in $top -x 0 -relx 0.449 -y 0 -rely 0.538 -width 20 -relwidth 0 \
        -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $top.but106 \
        -in $top -x 0 -relx 0.449 -y 0 -rely 0.615 -width 20 -relwidth 0 \
        -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $top.but107 \
        -in $top -x 0 -relx 0.449 -y 0 -rely 0.692 -width 20 -relwidth 0 \
        -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $top.but108 \
        -in $top -x 0 -relx 0.449 -y 0 -rely 0.769 -width 20 -relwidth 0 \
        -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $top.but109 \
        -in $top -x 0 -relx 0.449 -y 0 -rely 0.846 -width 20 -relwidth 0 \
        -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $top.but110 \
        -in $top -x 0 -relx 0.449 -y 0 -rely 0.923 -width 20 -relwidth 0 \
        -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $top.but119 \
        -in $top -x 0 -relx 0.664 -y 0 -rely 0.923 -width 20 -relwidth 0 \
        -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $top.but118 \
        -in $top -x 0 -relx 0.664 -y 0 -rely 0.846 -width 20 -relwidth 0 \
        -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $top.but117 \
        -in $top -x 0 -relx 0.664 -y 0 -rely 0.769 -width 20 -relwidth 0 \
        -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $top.but116 \
        -in $top -x 0 -relx 0.664 -y 0 -rely 0.692 -width 20 -relwidth 0 \
        -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $top.but115 \
        -in $top -x 0 -relx 0.664 -y 0 -rely 0.615 -width 20 -relwidth 0 \
        -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $top.but114 \
        -in $top -x 0 -relx 0.664 -y 0 -rely 0.538 -width 20 -relwidth 0 \
        -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $top.but113 \
        -in $top -x 0 -relx 0.664 -y 0 -rely 0.462 -width 20 -relwidth 0 \
        -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $top.but112 \
        -in $top -x 0 -relx 0.664 -y 0 -rely 0.385 -width 20 -relwidth 0 \
        -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $top.but111 \
        -in $top -x 0 -relx 0.664 -y 0 -rely 0.308 -width 20 -relwidth 0 \
        -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $top.but69 \
        -in $top -x 0 -relx 0.664 -y 0 -rely 0.231 -width 20 -relwidth 0 \
        -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $top.ent47 \
        -in $top -x 0 -relx 0.75 -y 0 -rely 0.077 -width 24 -relwidth 0 \
        -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $top.ent49 \
        -in $top -x 0 -relx 0.824 -y 0 -rely 0.077 -width 24 -relwidth 0 \
        -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $top.ent48 \
        -in $top -x 0 -relx 0.787 -y 0 -rely 0.077 -width 24 -relwidth 0 \
        -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $top.but120 \
        -in $top -x 0 -relx 0.873 -y 0 -rely 0.077 -width 87 -relwidth 0 \
        -height 20 -relheight 0 -anchor nw -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

proc 36 {args} {return 1}


Window show .
set btop1 ""
if {$vTcl(borrow)} {
    set btop1 .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop1 $vTcl(tops)] != -1} {
        set btop1 .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop1
Window show .top1 $btop1
if {$vTcl(borrow)} {
    $btop1 configure -background plum
}

