#! /usr/bin/env python3
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 8.0
#  in conjunction with Tcl version 8.6
#    Feb 07, 2024 01:51:24 PM CET  platform: Windows NT

from ast import Interactive
import sys
import tkinter as tk
import tkinter.ttk as ttk
from tkinter.constants import *
import numpy as np
from utility.serial import *
import normal_vectors
import serial
import ui
import struct


_debug = True # False to eliminate debug printing from callback functions.

def main(*args):
    '''Main entry point for the application.'''
    global root
    root = tk.Tk()
    root.protocol( 'WM_DELETE_WINDOW' , on_closing)
    # Creates a toplevel widget.
    global _top1, _w1
    global positions
    global ser_mot, connected, arm, permutation, was_reseted
    ser_mot=serial.Serial(None, 115200,timeout=None) 
    connected=False
    was_reseted=True
    positions =np.zeros(36)
    _top1 = root
    _w1 = ui.Toplevel1(_top1)
    _w1.angle.set(45)
    _w1.com.set(20)
    r=56.5
    h=107
    r_rolle=9
    arm=normal_vectors.continuum_arm(h,r,r_rolle,12.0)
    permutation=[6,8,7,0,2,1,4,3,5]
    root.mainloop()
    
def on_closing():
    if connected:
        ser_mot.close()
    root.destroy()

def connect(*args):
    comport=int(_w1.com.get())
    connection="COM"+str(comport)
    ser_mot.port=connection
    ser_mot.open()
    connected=True
    print(connection, "connected")

def send_proto():
    ba=bytearray()
    for i in range(36):
        ba.extend(struct.pack("f",  positions[i]*np.pi/180.0))
        ba.extend(struct.pack("f",10))
        ba.extend(struct.pack("f",0))
        ba.extend(struct.pack("f",0))
    send_all(wrapper(ba),ser_mot)
    get_all(ser_mot)
    
def moven(*args):
    id=int(args[0])
    deg=int(_w1.angle.get())
    positions[id-1]-=deg
    send_proto()

def movep(*args):
    id=int(args[0])
    deg=int(_w1.angle.get())
    positions[id-1]+=deg
    send_proto()

def reset():
    for i in range(9):
        positions[i]=0
    send_proto()
    global was_reseted
    was_reseted=True

if __name__ == '__main__':
    ui.start_up()




