#############################################################################
# Generated by PAGE version 8.0
#  in conjunction with Tcl version 8.6
#  Sep 24, 2024 12:33:53 PM CEST  platform: Windows NT
set vTcl(timestamp) ""
if {![info exists vTcl(borrow)]} {
    ::vTcl::MessageBox -title Error -message  "You must open project files from within PAGE."
    exit}


set vTcl(actual_gui_font_dft_desc)  TkDefaultFont
set vTcl(actual_gui_font_dft_name)  TkDefaultFont
set vTcl(actual_gui_font_text_desc)  TkTextFont
set vTcl(actual_gui_font_text_name)  TkTextFont
set vTcl(actual_gui_font_fixed_desc)  TkFixedFont
set vTcl(actual_gui_font_fixed_name)  TkFixedFont
set vTcl(actual_gui_font_menu_desc)  TkMenuFont
set vTcl(actual_gui_font_menu_name)  TkMenuFont
set vTcl(actual_gui_font_tooltip_desc)  TkDefaultFont
set vTcl(actual_gui_font_tooltip_name)  TkDefaultFont
set vTcl(actual_gui_font_treeview_desc)  TkDefaultFont
set vTcl(actual_gui_font_treeview_name)  TkDefaultFont
########################################### 
set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) gray40
set vTcl(analog_color_p) #c3c3c3
set vTcl(analog_color_m) beige
set vTcl(tabfg1) black
set vTcl(tabfg2) white
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(actual_gui_menu_active_fg)  #000000
########################################### 
set vTcl(pr,autoalias) 1
set vTcl(pr,relative_placement) 1
set vTcl(mode) Relative
set vTcl(project_theme) default



proc vTclWindow.top1 {base} {
    global vTcl
    if {$base == ""} {
        set base .top1
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    set target $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -menu $top.m51 -background #d9d9d9 -highlightbackground #d9d9d9 \
        -highlightcolor #000000 
    wm focusmodel $top passive
    wm geometry $top 710x573+460+143
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 3972 1410
    wm minsize $top 120 1
    wm overrideredirect $top 0
    wm resizable $top 0 0
    wm deiconify $top
    set toptitle "Toplevel 0"
    wm title $top $toptitle
    namespace eval ::widgets::${top}::ClassOption {}
    set ::widgets::${top}::ClassOption(-toptitle) $toptitle
    vTcl:DefineAlias "$top" "Toplevel1" vTcl:Toplevel:WidgetProc "" 1
    set vTcl(real_top) {}
    menu "$top.m51" \
        -activebackground #d9d9d9 -activeforeground black \
        -font "-family {Segoe UI} -size 9" -tearoff 0 
    label "$top.lab62" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #d9d9d9 -compound left -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 9" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -text "1" 
    vTcl:DefineAlias "$top.lab62" "Label1" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $top.lab62
    label "$top.lab64" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #d9d9d9 -compound left -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 9" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -text "3" 
    vTcl:DefineAlias "$top.lab64" "Label1_1_1" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $top.lab64
    label "$top.lab65" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #d9d9d9 -compound left -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 9" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -text "4" 
    vTcl:DefineAlias "$top.lab65" "Label1_2" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $top.lab65
    label "$top.lab66" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #d9d9d9 -compound left -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 9" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -text "5" 
    vTcl:DefineAlias "$top.lab66" "Label1_3" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $top.lab66
    label "$top.lab67" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #d9d9d9 -compound left -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 9" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -text "6" 
    vTcl:DefineAlias "$top.lab67" "Label1_3_1" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $top.lab67
    label "$top.lab80" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #d9d9d9 -compound left -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 9" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -text "7" 
    vTcl:DefineAlias "$top.lab80" "Label1_3_1_1" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $top.lab80
    label "$top.lab81" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #d9d9d9 -compound left -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 9" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -text "8" 
    vTcl:DefineAlias "$top.lab81" "Label1_3_1_1_1" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $top.lab81
    label "$top.lab82" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #d9d9d9 -compound left -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 9" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -text "9" 
    vTcl:DefineAlias "$top.lab82" "Label1_4" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $top.lab82
    label "$top.lab83" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #d9d9d9 -compound left -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 9" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -text "10" 
    vTcl:DefineAlias "$top.lab83" "Label1_4_1" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $top.lab83
    label "$top.lab84" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #d9d9d9 -compound left -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 9" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -text "11" 
    vTcl:DefineAlias "$top.lab84" "Label1_4_2" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $top.lab84
    label "$top.lab47" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #d9d9d9 -compound left -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 9" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -text "12" 
    vTcl:DefineAlias "$top.lab47" "Label1_4_2_1" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $top.lab47
    entry "$top.ent49" \
        -background white -disabledforeground #a3a3a3 \
        -font "-family {Courier New} -size 10" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -insertbackground #000000 -selectbackground #d9d9d9 \
        -selectforeground black -width 44 
    vTcl:DefineAlias "$top.ent49" "Entry2" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $top.ent49
    label "$top.lab63" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #d9d9d9 -compound left -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 9" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -text "2" 
    vTcl:DefineAlias "$top.lab63" "Label1_1" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $top.lab63
    entry "$top.ent51" \
        -background white -disabledforeground #a3a3a3 \
        -font "-family {Courier New} -size 10" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -insertbackground #000000 -selectbackground #d9d9d9 \
        -selectforeground black -width 34 
    vTcl:DefineAlias "$top.ent51" "Entry4" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $top.ent51
    entry "$top.ent53" \
        -background white -disabledforeground #a3a3a3 \
        -font "-family {Courier New} -size 10" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -insertbackground #000000 -selectbackground #d9d9d9 \
        -selectforeground black -width 10 
    vTcl:DefineAlias "$top.ent53" "Entry6" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $top.ent53
    entry "$top.ent55" \
        -background white -disabledforeground #a3a3a3 \
        -font "-family {Courier New} -size 10" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -insertbackground #000000 -selectbackground #d9d9d9 \
        -selectforeground black -width 10 
    vTcl:DefineAlias "$top.ent55" "Entry8" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $top.ent55
    entry "$top.ent57" \
        -background white -disabledforeground #a3a3a3 \
        -font "-family {Courier New} -size 10" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -insertbackground #000000 -selectbackground #d9d9d9 \
        -selectforeground black -width 44 
    vTcl:DefineAlias "$top.ent57" "Entry10" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $top.ent57
    entry "$top.ent59" \
        -background white -disabledforeground #a3a3a3 \
        -font "-family {Courier New} -size 10" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -insertbackground #000000 -selectbackground #d9d9d9 \
        -selectforeground black -width 44 
    vTcl:DefineAlias "$top.ent59" "Entry12" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $top.ent59
    entry "$top.ent68" \
        -background white -disabledforeground #a3a3a3 \
        -font "-family {Courier New} -size 10" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -insertbackground #000000 -selectbackground #d9d9d9 \
        -selectforeground black -width 44 
    vTcl:DefineAlias "$top.ent68" "Entry14" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $top.ent68
    entry "$top.ent70" \
        -background white -disabledforeground #a3a3a3 \
        -font "-family {Courier New} -size 10" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -insertbackground #000000 -selectbackground #d9d9d9 \
        -selectforeground black -width 44 
    vTcl:DefineAlias "$top.ent70" "Entry16" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $top.ent70
    entry "$top.ent72" \
        -background white -disabledforeground #a3a3a3 \
        -font "-family {Courier New} -size 10" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -insertbackground #000000 -selectbackground #d9d9d9 \
        -selectforeground black -width 44 
    vTcl:DefineAlias "$top.ent72" "Entry18" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $top.ent72
    entry "$top.ent74" \
        -background white -disabledforeground #a3a3a3 \
        -font "-family {Courier New} -size 10" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -insertbackground #000000 -selectbackground #d9d9d9 \
        -selectforeground black -width 44 
    vTcl:DefineAlias "$top.ent74" "Entry20" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $top.ent74
    entry "$top.ent52" \
        -background white -disabledforeground #a3a3a3 \
        -font "-family {Courier New} -size 10" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -insertbackground #000000 -selectbackground #d9d9d9 \
        -selectforeground black -width 10 
    vTcl:DefineAlias "$top.ent52" "Entry5" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $top.ent52
    entry "$top.ent56" \
        -background white -disabledforeground #a3a3a3 \
        -font "-family {Courier New} -size 10" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -insertbackground #000000 -selectbackground #d9d9d9 \
        -selectforeground black -width 44 
    vTcl:DefineAlias "$top.ent56" "Entry9" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $top.ent56
    entry "$top.ent58" \
        -background white -disabledforeground #a3a3a3 \
        -font "-family {Courier New} -size 10" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -insertbackground #000000 -selectbackground #d9d9d9 \
        -selectforeground black -width 44 
    vTcl:DefineAlias "$top.ent58" "Entry11" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $top.ent58
    entry "$top.ent60" \
        -background white -disabledforeground #a3a3a3 \
        -font "-family {Courier New} -size 10" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -insertbackground #000000 -selectbackground #d9d9d9 \
        -selectforeground black -width 44 
    vTcl:DefineAlias "$top.ent60" "Entry13" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $top.ent60
    entry "$top.ent69" \
        -background white -disabledforeground #a3a3a3 \
        -font "-family {Courier New} -size 10" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -insertbackground #000000 -selectbackground #d9d9d9 \
        -selectforeground black -width 44 
    vTcl:DefineAlias "$top.ent69" "Entry15" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $top.ent69
    entry "$top.ent71" \
        -background white -disabledforeground #a3a3a3 \
        -font "-family {Courier New} -size 10" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -insertbackground #000000 -selectbackground #d9d9d9 \
        -selectforeground black -width 44 
    vTcl:DefineAlias "$top.ent71" "Entry17" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $top.ent71
    entry "$top.ent73" \
        -background white -disabledforeground #a3a3a3 \
        -font "-family {Courier New} -size 10" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -insertbackground #000000 -selectbackground #d9d9d9 \
        -selectforeground black -width 44 
    vTcl:DefineAlias "$top.ent73" "Entry19" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $top.ent73
    entry "$top.ent75" \
        -background white -disabledforeground #a3a3a3 \
        -font "-family {Courier New} -size 10" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -insertbackground #000000 -selectbackground #d9d9d9 \
        -selectforeground black -width 44 
    vTcl:DefineAlias "$top.ent75" "Entry21" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $top.ent75
    entry "$top.ent77" \
        -background white -disabledforeground #a3a3a3 \
        -font "-family {Courier New} -size 10" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -insertbackground #000000 -selectbackground #d9d9d9 \
        -selectforeground black -width 44 
    vTcl:DefineAlias "$top.ent77" "Entry23" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $top.ent77
    button "$top.but50" \
        -activebackground #d9d9d9 -activeforeground black -background #d9d9d9 \
        -disabledforeground #a3a3a3 -font "-family {Segoe UI} -size 9" \
        -foreground #000000 -highlightbackground #d9d9d9 \
        -highlightcolor #000000 -text "Reset" 
    vTcl:DefineAlias "$top.but50" "Button3" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $top.but50
    entry "$top.ent50" \
        -background white -disabledforeground #a3a3a3 \
        -font "-family {Courier New} -size 10" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -insertbackground #000000 -selectbackground #d9d9d9 \
        -selectforeground black -width 44 
    vTcl:DefineAlias "$top.ent50" "Entry3" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $top.ent50
    entry "$top.ent54" \
        -background white -disabledforeground #a3a3a3 \
        -font "-family {Courier New} -size 10" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -insertbackground #000000 -selectbackground #d9d9d9 \
        -selectforeground black -width 10 
    vTcl:DefineAlias "$top.ent54" "Entry7" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $top.ent54
    button "$top.but48" \
        -activebackground #d9d9d9 -activeforeground black -background #d9d9d9 \
        -command "connect()" -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 9" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -text "Connect" 
    vTcl:DefineAlias "$top.but48" "Button1" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $top.but48
    entry "$top.ent47" \
        -background white -disabledforeground #a3a3a3 \
        -font "-family {Courier New} -size 10" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -insertbackground #000000 -selectbackground #d9d9d9 \
        -selectforeground black -width 10 
    vTcl:DefineAlias "$top.ent47" "com" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $top.ent47
    entry "$top.ent79" \
        -background white -disabledforeground #a3a3a3 \
        -font "-family {Courier New} -size 10" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -insertbackground #000000 -selectbackground #d9d9d9 \
        -selectforeground black -width 44 
    vTcl:DefineAlias "$top.ent79" "Entry25" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $top.ent79
    entry "$top.ent78" \
        -background white -disabledforeground #a3a3a3 \
        -font "-family {Courier New} -size 10" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -insertbackground #000000 -selectbackground #d9d9d9 \
        -selectforeground black -width 44 
    vTcl:DefineAlias "$top.ent78" "Entry24" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $top.ent78
    entry "$top.ent76" \
        -background white -disabledforeground #a3a3a3 \
        -font "-family {Courier New} -size 10" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -insertbackground #000000 -selectbackground #d9d9d9 \
        -selectforeground black -width 44 
    vTcl:DefineAlias "$top.ent76" "Entry22" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $top.ent76
    button "$top.but49" \
        -activebackground #d9d9d9 -activeforeground black -background #d9d9d9 \
        -disabledforeground #a3a3a3 -font "-family {Segoe UI} -size 9" \
        -foreground #000000 -highlightbackground #d9d9d9 \
        -highlightcolor #000000 -text "Move" 
    vTcl:DefineAlias "$top.but49" "Button2" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $top.but49
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.lab62 \
        -in $top -x 0 -relx 0.07 -y 0 -rely 0.09 -width 0 -relwidth 0.048 \
        -height 0 -relheight 0.038 -anchor nw -bordermode ignore 
    place $top.lab64 \
        -in $top -x 0 -relx 0.07 -y 0 -rely 0.199 -width 0 -relwidth 0.048 \
        -height 0 -relheight 0.038 -anchor nw -bordermode ignore 
    place $top.lab65 \
        -in $top -x 0 -relx 0.07 -y 0 -rely 0.253 -width 0 -relwidth 0.048 \
        -height 0 -relheight 0.038 -anchor nw -bordermode ignore 
    place $top.lab66 \
        -in $top -x 0 -relx 0.07 -y 0 -rely 0.307 -width 0 -relwidth 0.048 \
        -height 0 -relheight 0.038 -anchor nw -bordermode ignore 
    place $top.lab67 \
        -in $top -x 0 -relx 0.07 -y 0 -rely 0.362 -width 0 -relwidth 0.048 \
        -height 0 -relheight 0.038 -anchor nw -bordermode ignore 
    place $top.lab80 \
        -in $top -x 0 -relx 0.07 -y 0 -rely 0.416 -width 0 -relwidth 0.048 \
        -height 0 -relheight 0.038 -anchor nw -bordermode ignore 
    place $top.lab81 \
        -in $top -x 0 -relx 0.07 -y 0 -rely 0.47 -width 0 -relwidth 0.048 \
        -height 0 -relheight 0.038 -anchor nw -bordermode ignore 
    place $top.lab82 \
        -in $top -x 0 -relx 0.07 -y 0 -rely 0.524 -width 0 -relwidth 0.048 \
        -height 0 -relheight 0.038 -anchor nw -bordermode ignore 
    place $top.lab83 \
        -in $top -x 0 -relx 0.07 -y 0 -rely 0.579 -width 0 -relwidth 0.048 \
        -height 0 -relheight 0.038 -anchor nw -bordermode ignore 
    place $top.lab84 \
        -in $top -x 0 -relx 0.07 -y 0 -rely 0.633 -width 0 -relwidth 0.048 \
        -height 0 -relheight 0.038 -anchor nw -bordermode ignore 
    place $top.lab47 \
        -in $top -x 0 -relx 0.07 -y 0 -rely 0.687 -width 0 -relwidth 0.048 \
        -height 0 -relheight 0.038 -anchor nw -bordermode ignore 
    place $top.ent49 \
        -in $top -x 0 -relx 0.127 -y 0 -rely 0.09 -width 44 -relwidth 0 \
        -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $top.lab63 \
        -in $top -x 0 -relx 0.07 -y 0 -rely 0.145 -width 0 -relwidth 0.048 \
        -height 0 -relheight 0.038 -anchor nw -bordermode ignore 
    place $top.ent51 \
        -in $top -x 0 -relx 0.127 -y 0 -rely 0.145 -width 44 -relwidth 0 \
        -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $top.ent53 \
        -in $top -x 0 -relx 0.127 -y 0 -rely 0.199 -width 44 -relwidth 0 \
        -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $top.ent55 \
        -in $top -x 0 -relx 0.127 -y 0 -rely 0.253 -width 44 -relwidth 0 \
        -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $top.ent57 \
        -in $top -x 0 -relx 0.127 -y 0 -rely 0.307 -width 44 -relwidth 0 \
        -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $top.ent59 \
        -in $top -x 0 -relx 0.127 -y 0 -rely 0.362 -width 44 -relwidth 0 \
        -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $top.ent68 \
        -in $top -x 0 -relx 0.127 -y 0 -rely 0.416 -width 44 -relwidth 0 \
        -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $top.ent70 \
        -in $top -x 0 -relx 0.127 -y 0 -rely 0.47 -width 44 -relwidth 0 \
        -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $top.ent72 \
        -in $top -x 0 -relx 0.127 -y 0 -rely 0.524 -width 44 -relwidth 0 \
        -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $top.ent74 \
        -in $top -x 0 -relx 0.127 -y 0 -rely 0.579 -width 44 -relwidth 0 \
        -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $top.ent52 \
        -in $top -x 0 -relx 0.211 -y 0 -rely 0.145 -width 44 -relwidth 0 \
        -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $top.ent56 \
        -in $top -x 0 -relx 0.211 -y 0 -rely 0.253 -width 44 -relwidth 0 \
        -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $top.ent58 \
        -in $top -x 0 -relx 0.211 -y 0 -rely 0.307 -width 44 -relwidth 0 \
        -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $top.ent60 \
        -in $top -x 0 -relx 0.211 -y 0 -rely 0.362 -width 44 -relwidth 0 \
        -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $top.ent69 \
        -in $top -x 0 -relx 0.211 -y 0 -rely 0.416 -width 44 -relwidth 0 \
        -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $top.ent71 \
        -in $top -x 0 -relx 0.211 -y 0 -rely 0.47 -width 44 -relwidth 0 \
        -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $top.ent73 \
        -in $top -x 0 -relx 0.211 -y 0 -rely 0.524 -width 44 -relwidth 0 \
        -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $top.ent75 \
        -in $top -x 0 -relx 0.211 -y 0 -rely 0.579 -width 44 -relwidth 0 \
        -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $top.ent77 \
        -in $top -x 0 -relx 0.211 -y 0 -rely 0.633 -width 44 -relwidth 0 \
        -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $top.but50 \
        -in $top -x 0 -relx 0.211 -y 0 -rely 0.741 -width 47 -relwidth 0 \
        -height 26 -relheight 0 -anchor nw -bordermode ignore 
    place $top.ent50 \
        -in $top -x 0 -relx 0.211 -y 0 -rely 0.09 -width 44 -relwidth 0 \
        -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $top.ent54 \
        -in $top -x 0 -relx 0.211 -y 0 -rely 0.199 -width 44 -relwidth 0 \
        -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $top.but48 \
        -in $top -x 0 -relx 0.493 -y 0 -rely 0.018 -width 57 -relwidth 0 \
        -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $top.ent47 \
        -in $top -x 0 -relx 0.352 -y 0 -rely 0.018 -width 84 -relwidth 0 \
        -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $top.ent79 \
        -in $top -x 0 -relx 0.211 -y 0 -rely 0.687 -width 44 -relwidth 0 \
        -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $top.ent78 \
        -in $top -x 0 -relx 0.127 -y 0 -rely 0.687 -width 44 -relwidth 0 \
        -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $top.ent76 \
        -in $top -x 0 -relx 0.127 -y 0 -rely 0.633 -width 44 -relwidth 0 \
        -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $top.but49 \
        -in $top -x 0 -relx 0.127 -y 0 -rely 0.741 -width 47 -relwidth 0 \
        -height 26 -relheight 0 -anchor nw -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

proc 36 {args} {return 1}


Window show .
set btop1 ""
if {$vTcl(borrow)} {
    set btop1 .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop1 $vTcl(tops)] != -1} {
        set btop1 .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop1
Window show .top1 $btop1
if {$vTcl(borrow)} {
    $btop1 configure -background plum
}

