#! /usr/bin/env python3
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 8.0
#  in conjunction with Tcl version 8.6
#    Feb 07, 2024 01:51:24 PM CET  platform: Windows NT

from ast import Interactive
import sys
import tkinter as tk
import tkinter.ttk as ttk
from tkinter.constants import *
import numpy as np

import ui

_debug = True # False to eliminate debug printing from callback functions.

def main(*args):
    '''Main entry point for the application.'''
    global root
    root = tk.Tk()
    root.protocol( 'WM_DELETE_WINDOW' , root.destroy)
    # Creates a toplevel widget.
    global _top1, _w1
    global positions
    positions =np.zeros(9)
    _top1 = root
    _w1 = ui.Toplevel1(_top1)
    _w1.angle.set(45)
    _w1.angle.set(15)
    root.mainloop()

def connect(*args):
    comport=int(_w1.com.get())
    connection="COM"+str(comport)
    print(connection)
def moven(*args):
    id=int(args[0])
    deg=int(_w1.angle.get())
    positions[id]-=deg
    print(positions[id])
    
    sys.stdout.flush()

def movep(*args):
    id=int(args[0])
    deg=int(_w1.angle.get())
    positions[id]+=deg
    print(positions[id])
    
    sys.stdout.flush()   


if __name__ == '__main__':
    ui.start_up()




